## 1. แสดงข้อมูลเชิงสถิติ

### เริ่มจากนำเข้าข้อมูล

In [10]:
import pandas as pd
data_daily = pd.read_csv("../data/stations_daily.csv")
data_hourly = pd.read_csv("../data/stations_hourly.csv")

### แสดงสถิติคร่าวๆ ของ ไฟล์รายวัน

In [11]:
describe_col = data_daily.columns
describe_col = describe_col[2:] # ไม่เอา column แรก (station_id)
data_daily.describe()[describe_col]

,PM2.5,PM10,NOx,O3,CO,HR,NO,NO2,TMP,BEN,...,HCT,HRI,IUV,PB,PP,PST,RS,TMPI,UVA,XIL
count,1.616980e+05,1.804810e+05,1.128810e+05,192957.000000,175493.000000,1.232850e+05,1.181540e+05,1.692860e+05,127015.000000,775.000000,...,0.0,10205.000000,4936.000000,91738.000000,75346.000000,0.0,7.550700e+04,34385.000000,16090.000000,775.000000
mean,2.226160e+33,1.307211e+33,2.853819e+01,0.405834,5.589823,2.277640e+02,2.712090e+01,1.896445e+01,24.111527,1.133146,...,NaN,51.672491,3.292230,638.512285,289.717806,NaN,2.576214e+02,21.619134,9.618918,0.160362
std,5.500417e+35,3.680391e+35,9.493952e+03,121.093397,336.347484,5.022662e+04,9.279685e+03,7.752592e+03,626.585152,5.297612,...,NaN,14.434358,4.691052,531.870733,3381.823375,NaN,3.818544e+03,49.563922,11.173551,0.040744
min,0.000000e+00,0.000000e+00,0.000000e+00,0.000000,0.000000,0.000000e+00,0.000000e+00,0.000000e+00,0.000000,0.000000,...,NaN,10.625000,0.000000,0.000000,0.000000,NaN,0.000000e+00,0.028861,0.000000,0.000000
25%,1.290000e+01,3.187417e+01,1.415417e-02,0.018483,0.531426,4.344420e+01,4.891667e-03,9.441667e-03,15.920833,0.474877,...,NaN,40.600000,1.669847,594.452532,0.000000,NaN,1.278333e+02,18.590417,4.826148,0.148062
50%,1.960000e+01,4.738759e+01,2.396125e-02,0.025333,0.791667,5.752618e+01,1.002175e-02,1.600592e-02,19.181694,0.620833,...,NaN,52.145833,2.596838,623.954918,0.000000,NaN,1.923212e+02,21.083125,7.958869,0.164625
75%,2.811156e+01,6.767537e+01,3.937500e-02,0.033375,1.202778,6.912458e+01,2.020833e-02,2.477273e-02,22.960761,0.780195,...,NaN,63.829167,3.578432,703.270833,0.001667,NaN,2.660833e+02,23.195750,11.425276,0.181533
max,1.806160e+38,1.412893e+38,3.189756e+06,53185.473851,84087.353799,1.736131e+07,3.189756e+06,3.189756e+06,202409.533333,67.000000,...,NaN,104.041583,49.026343,146623.557916,221817.210000,NaN,1.041948e+06,8268.433333,639.626234,0.273958

### แสดงสถิติคร่าวๆ ของ ไฟล์รายชั่วโมง

In [12]:
describe_col = data_hourly.columns
describe_col = describe_col[2:] # ไม่เอา column แรก (station_id)
data_hourly.describe()[describe_col]

,PM2.5,PM10,NOx,O3,CO,HR,NO,NO2,TMP,BEN,...,HCT,HRI,IUV,PB,PP,PST,RS,TMPI,UVA,XIL
count,4.051918e+06,4.637964e+06,3.046803e+06,4.914802e+06,4.542033e+06,3.388063e+06,3.134901e+06,4.344013e+06,3.467518e+06,18323.000000,...,0.0,777220.000000,108849.000000,2.099985e+06,2.267195e+06,0.0,1.653531e+06,1.378079e+06,375454.000000,18323.000000
mean,1.575017e+33,7.423936e+32,3.370523e+00,2.235814e-01,4.293768e+00,2.091774e+02,3.159406e+00,2.309685e+00,2.084149e+01,1.116749,...,NaN,45.691136,2.882683,6.369050e+02,2.122435e+02,NaN,2.501316e+02,1.953389e+01,9.425129,0.161002
std,8.354006e+35,4.069897e+35,3.181981e+03,1.525898e+02,4.671265e+02,2.299328e+05,3.136951e+03,2.664859e+03,6.214520e+02,5.801153,...,NaN,11.800020,5.113522,5.261369e+02,3.726876e+03,NaN,1.945145e+04,4.802932e+01,19.065279,0.091871
min,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000,...,NaN,7.000000,0.000000,0.000000e+00,0.000000e+00,NaN,0.000000e+00,1.037500e-02,0.000000,0.000000
25%,1.100000e+01,2.536100e+01,1.141000e-02,8.000000e-03,4.300000e-01,4.156241e+01,3.000000e-03,8.000000e-03,1.210000e+01,0.000000,...,NaN,36.700000,0.000000,5.938645e+02,0.000000e+00,NaN,1.000000e+00,1.624000e+01,0.201952,0.096000
50%,1.800000e+01,4.108353e+01,2.200000e-02,1.970710e-02,7.200000e-01,6.297000e+01,7.280000e-03,1.520973e-02,1.763626e+01,0.500000,...,NaN,43.700000,0.254167,6.235941e+02,0.000000e+00,NaN,3.800000e+01,1.789000e+01,2.600133,0.160600
75%,2.900000e+01,6.500000e+01,4.276215e-02,3.579000e-02,1.270000e+00,7.900000e+01,2.190000e-02,2.500000e-02,2.309000e+01,1.000000,...,NaN,53.600000,3.988889,7.017000e+02,0.000000e+00,NaN,3.860000e+02,2.215500e+01,13.625467,0.209000
max,4.924800e+38,2.640400e+38,3.422585e+06,2.023916e+05,6.947900e+05,4.166700e+08,3.422585e+06,3.422585e+06,4.208200e+05,133.000000,...,NaN,124.870000,117.276343,1.509499e+05,2.218172e+05,NaN,2.500000e+07,2.892800e+04,7035.888579,0.360000

### แสดงการกระจายข้อมูล

In [13]:
import numpy as np

In [14]:
describe_col
np.var(data_daily[describe_col], axis=0)

PM2.5    3.025441e+71
PM10     1.354520e+71
NOx      9.013432e+07
O3       1.466353e+04
CO       1.131290e+05
HR       2.522693e+09
NO       8.611182e+07
NO2      6.010233e+07
TMP      3.926059e+05
BEN      2.802848e+01
CH4      4.216556e+03
CN       1.351639e+05
CO2      3.197416e+02
H2S      2.771908e-04
HCNM     5.756027e+03
HCT               NaN
HRI      2.083303e+02
IUV      2.200151e+01
PB       2.828834e+05
PP       1.143658e+07
PST               NaN
RS       1.458109e+07
TMPI     2.456511e+03
UVA      1.248405e+02
XIL      1.657892e-03
dtype: float64

สังเกตว่าข้อมูลมีความแปรปรวนสูงมาก (ช่วงของค่ากว้างมากๆ)

In [15]:
describe_col
np.var(data_hourly[describe_col], axis=0)

ทางไฟล์รายชั่วโมงก็เช่นกัน

In [ ]:
data_daily.isna().sum()

datetime           0
station_id         0
PM2.5          69894
PM10           51111
NOx           118711
O3             38635
CO             56099
HR            108307
NO            113438
NO2            62306
TMP           104577
BEN           230817
CH4           231322
CN            230997
CO2           231536
H2S           231312
HCNM          231313
HCT           231592
HRI           221387
IUV           226656
PB            139854
PP            156246
PST           231592
RS            156085
TMPI          197207
UVA           215502
XIL           230817
dtype: int64

In [ ]:
data_hourly.isna().sum()

datetime            0
station_id          0
PM2.5         1899985
PM10          1313939
NOx           2905100
O3            1037101
CO            1409870
HR            2563840
NO            2817002
NO2           1607890
TMP           2484385
BEN           5933580
CH4           5947689
CN            5939258
CO2           5950584
H2S           5947229
HCNM          5947525
HCT           5951903
HRI           5174683
IUV           5843054
PB            3851918
PP            3684708
PST           5951903
RS            4298372
TMPI          4573824
UVA           5576449
XIL           5933580
dtype: int64

และข้อมูลว่างเยอะมาก

**ต่อไปก็เริ่มขั้นตอนที่ 2  (การทำความสะอาดข้อมูล หรือคัดกรองข้อมูล)**